<p style="text-align: justify;"><strong>Background</strong>: The cost for high resolution pipeline inspection can range from roughly $2000 to $6000 per mile. Pipeline repairs are costly and dangerous, and preventative measures are frequently taken by companies to minimize risk and the advent of future problems. Our final year capstone project involved developing an imaging system to automate the inspection process for oil and gas wells .</p>
<p style="text-align: justify;"><strong>Objective</strong>: Develop an optical scanning system to be used for generating 3D models of well liners and casings with sub-millimeter accuracy.</p>
<p style="text-align: justify;"><strong style="line-height: 27px;">How</strong><span style="line-height: 27px;">: As a team of five mechatronic and mechanical engineering students, we designed and constructed an alpha prototype of the optical 3D well imager.</span></p>
<strong>Client</strong>: DarkVision Technologies
<h3><strong>Requirements and Specifications</strong></h3>
<p style="display: inline !important;"><strong>Optical</strong></p>

<ol>
 	<li>Device must have a tolerance on distance measurement of 1 mm</li>
 	<li>Device must have a camera circumferential resolution of 1.42°</li>
 	<li>Device must have a 3D scan circumferential resolution of 1.42°</li>
 	<li>Device must have an axial resolution of 1 mm</li>
</ol>
<strong>Mechanical</strong>
<ol>
 	<li>Device must be submersible</li>
 	<li>Device must fit in a 3.5” ID pipe</li>
 	<li>Device must have a minimum operating velocity of 10 mm/s</li>
 	<li>Device must be operable using the existing test apparatus</li>
</ol>
<h3><strong>Design Overview</strong></h3>
<p style="text-align: justify;">The final design of the prototype includes a camera module, laser module, and two conical mirrors. The basic functionality of the device is shown in the figure below. A red laser ring is generated by the laser module which is reflected by 90° on to the surface of the well casing. The camera’s vision is then reflected by 150° to capture the projected laser ring.</p>


[caption id="attachment_676" align="aligncenter" width="620"]<a href="http://www.justinmklam.com/wp-content/uploads/System-overview.png" target="_blank"><img class="wp-image-676 size-large" src="http://www.justinmklam.com/wp-content/uploads/System-overview-1024x300.png" alt="System overview" width="620" height="182" /></a> Simplified diagram of scanning functionality.[/caption]

<strong>Combined Modules</strong>

[caption id="attachment_696" align="aligncenter" width="620"]<a href="http://www.justinmklam.com/wp-content/uploads/Annotated-Combined-Modules_2-1.png"><img class="size-large wp-image-696" src="http://www.justinmklam.com/wp-content/uploads/Annotated-Combined-Modules_2-1-1024x493.png" alt="Overview of the optical imaging device." width="620" height="298" /></a> Overview of the optical imaging device.[/caption]

<strong>Camera Module</strong>

[caption id="attachment_677" align="aligncenter" width="620"]<a href="http://www.justinmklam.com/wp-content/uploads/Camera-Module.png"><img class="wp-image-677 size-large" src="http://www.justinmklam.com/wp-content/uploads/Camera-Module-1024x756.png" alt="Camera Module" width="620" height="458" /></a> Diagram of the camera module.[/caption]

<strong>Laser Module</strong>

[caption id="attachment_675" align="aligncenter" width="620"]<a href="http://www.justinmklam.com/wp-content/uploads/Laser-Module.png" target="_blank"><img class="wp-image-675 size-large" src="http://www.justinmklam.com/wp-content/uploads/Laser-Module-1024x631.png" alt="Laser Module" width="620" height="382" /></a> Diagram of the laser module.[/caption]
<h3>System Evaluation</h3>
<p style="text-align: justify;">Our prototype was successful in recreating a 3D model of the pipe internals during unsubmerged operation, as shown through the figures below. However, we were unable to test the device in submerged conditions due to time constraints of the project.</p>
<p style="text-align: justify;"><strong>Preliminary Testing and Calibration</strong></p>


[caption id="attachment_689" align="aligncenter" width="620"]<a href="http://www.justinmklam.com/wp-content/uploads/System-evaluation_5.png"><img class="size-large wp-image-689" src="http://www.justinmklam.com/wp-content/uploads/System-evaluation_5-1024x495.png" alt="Setup of the calibration grid with a green laser ring (left); Captured image (right)." width="620" height="300" /></a> Setup of the calibration grid with a green laser ring (left); Captured image (right).[/caption]

<strong>Device Integration</strong>

[caption id="attachment_685" align="aligncenter" width="620"]<a href="http://www.justinmklam.com/wp-content/uploads/System-evaluation_2.png"><img class="size-large wp-image-685" src="http://www.justinmklam.com/wp-content/uploads/System-evaluation_2-1024x498.png" alt="Our device installed with the DarkVision lab equipment (left); Close up of the laser ring inside the well liner (right)." width="620" height="302" /></a> Our device installed with the DarkVision lab equipment (left); Close up of the laser ring inside the well liner (right).[/caption]

<strong>Post-Processing and Analysis</strong>
<p style="text-align: justify;">Four different exposure times and traversing speeds were tested to determine which camera parameters would generate adequate images for post-processing and analysis. From our tests, we determined that the imaging parameters resulting in an effective frame rate of 0.13 fps at a forward jog speed of 7 mm/s showed the most promising image slices of the well liner. To increase the slice resolution of the scan, the frame rate was increased to 1.3 fps which yielded visually poorer images, but our processing algorithms were still able to generate a 3D model of the well liner. A hue saturation value filter was used to detect the outer edge of the raw image.</p>


[caption id="attachment_686" align="aligncenter" width="935"]<a href="http://www.justinmklam.com/wp-content/uploads/System-evaluation_3.png"><img class="size-full wp-image-686" src="http://www.justinmklam.com/wp-content/uploads/System-evaluation_3.png" alt="Captured laser ring by the camera through the conical mirror (left); Processed image (right)." width="935" height="451" /></a> Captured laser ring by the camera through the conical mirror (left); Processed image (right).[/caption]

[caption id="attachment_691" align="aligncenter" width="460"]<a href="http://www.justinmklam.com/wp-content/uploads/System-evaluation_4-1.png"><img class="size-full wp-image-691" src="http://www.justinmklam.com/wp-content/uploads/System-evaluation_4-1.png" alt="Generated 3D model from the image slices." width="460" height="252" /></a> Generated 3D model from the image slices.[/caption]